development:
  adapter: postgresql
  encoding: unicode
  database: sinatra_api_backend_app
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

production:
  adapter: postgresql
  encoding: unicode
  database: sinatra_api_backend_app
  pool: 5
  username: 
  password: 